### PR TITLE
Allow libphobos to build on FreeBSD/PowerPC64

### PR DESCRIPTION
**Pull request by lenoil98**
Add support for FreeBSD on PowerPC64.

### CODE REVIEW

**Comment by ibuclaw** [comment]
> Add support for FreeBSD on PowerPC64.

Has this been tested though? Note that you can override configure.tgt by passing `--enable-libphobos` to configure.

**Comment by lenoil98** [comment]
Yes.  I’ve tested this on both PowerPC64 BE and LE. I’ve used it to build `dub` along with some D libs and tools from ports.

**Comment by ibuclaw** [comment]
> Yes. I’ve tested this on both PowerPC64 BE and LE. I’ve used it to build `dub` along with some D libs and tools from ports.

What is the "long double" type used for FreeBSD?  Surely you can't have gotten past building std.math with IBM reals. :-)

**Comment by lenoil98** [comment]
> What is the "long double" type used for FreeBSD? Surely you can't have gotten past building std.math with IBM reals. :-)

Not sure this is what you’re looking for, but `long double size is 8` same as double.  The config file states the .gnu.attributes is used for long double, if that makes a difference.

Everything compiles without error. :-)

**Comment by ibuclaw** [comment]
> > What is the "long double" type used for FreeBSD? Surely you can't have gotten past building std.math with IBM reals. :-)
> 
> Not sure this is what you’re looking for, but `long double size is 8` same as double. The config file states the .gnu.attributes is used for long double, if that makes a difference.
> 
> Everything compiles without error. :-)

OK, that just tells me that FreeBSD may not support 128bit reals (Linux and OSX PPC does).

**Comment by ibuclaw** [comment]
OK confirmed, only Linux and Darwin set the long double size to 128.

**Comment by ibuclaw** [comment]
This has been added to mainline and backported to releases/gcc-11.

**Pull request closed without merging**
