### PR TITLE
trunk-next rebase  46c910d 

### PR DESCRIPTION
**Pull request by belka-ew**
The PR should be probably against the `trunk` branch?

### CODE REVIEW

**Comment by jpf91** [comment]
Nice work! The PR itself should target `trunk-next`, but the rebase should be done on `trunk` or `trunk-ci`. Just make sure to delete the `ce9692b53b82e3b4b266134349dfff089b67d5f3` commit from the `trunk-next` branch in some way. I'd rebase on trunk-ci then, as it will include a new `Add CI files` commit for the CI setup.

**Comment by belka-ew** [comment]
Updated and rebased on trunk.

**Comment by jpf91** [comment]
@belka-ew shall we merge this into the trunk-next branch? @ibuclaw any comment / does this need further review?

@belka-ew now I understand why you asked whether this should target trunk/trunk-ci. We'll have to push manually anyway, as the github UI can't merge this rebased branch. Also, it would indeed be much nicer for diffing/reviewing to have only the changes compared to trunk. So it may really be better if you open a new PR targeting trunk instead.

**Comment by belka-ew** [comment]
Updated.

@jpf91 I changed the base branch to `trunk`. If you give your ok, I would just force-push it to `trunk-next` or you can do it if you want.

Btw. this rebasing thing is not very nice for reviews since the one before the last commit contains the whole DMD frontend - so the latest changes can't be reviewed separtely. But I don't see a better way to do it. Either the whole D frontend or unrelated GCC changes (when merging instead of rebasing) are in the diff.

**Comment by jpf91** [comment]
@belka-ew Looks great, feel free to push this to trunk-next!

Regarding the rebase:  I agree it's not nice for review, but I don't think we can do anything else. In the end, once GCC9 is released, we'll actually have to push this one giant commit (DDMD converion) to GCC upstream anyway. So there's no other way to do this (I think merges would not really work if we want to push the changes to GCC SVN later on). Maybe we can split that commit into Makefile/DMD/phobos changes though, once the time comes to push to upstream.

There's one thing we can do though: Continue to rebase on GCC-trunk, so the DDMD conversion will be in one commit, not much we can do there. But if you're going to update from upstream (frontend, phobos), you can create new commits for these in this branch. You should still be able to rebase the whole branch on trunk in that case.

BTW: Something seems broken with the CI for the phobos unittests, but that problem seems to also affect the trunk branch.

**Comment by jpf91** [comment]
@belka-ew Btw, which DMD commit is this based on? I think you forgot to update the gcc/d/dmd/merge file? ;-)

**Comment by belka-ew** [comment]
Is MERGE from cxxdmd and ddmd the same?

- MERGE in cxxdmd seems to mean: I merge commits from dmd selectively and MERGE is the last commit I ported to cxxdmd
- MERGE in ddmd: I merge the complete D frontend and MERGE contains the state of the D frontend in GCC

The state of the D frontend in the ddmd version is 2.081.2 + some backports. I actually wasn't sure about the content of MERGE for ddmd and left it alone hoping that nobody notices it. But I'd happy to fix it if needed or wait for the update of the whole frontend (I started slowly working on it).

**Comment by jpf91** [comment]
I'd say it's mostly the same:
* in cxxdmd: The commit is the id of the last merged commit of the dmd `dmd-cxx` branch.
* in ddmd: The commit is the id of the last merged commit of the dmd `master` branch.

In both cases you could still have some additional backported commits. The commit ID basically just tells us developers that all commits following that commit on the `dmd-cxx` or dmd `master` branches have not been integrated into GDC yet and need to be looked at.

However, If that commit  is not known for this latest DDMD state (it's probably the commit with the 2.081.2 tag?) we can just update the ID in the next DMD merge.

**Comment by belka-ew** [comment]
Thans for the explanation. Actually it is newer than 2.081.2. I suppose the last one is this one:
https://github.com/D-Programming-GDC/gdc-archived/pull/765 (76d619c28590c632d01e8b0840b358acdf141357). Correct?

**Comment by jpf91** [comment]
Yes, 76d619c28590c632d01e8b0840b358acdf141357 indeed seems to be the correct commit :+1:

**Pull request closed without merging**
