### PR TITLE
[libphobos] Update info about required autotools versions

### PR DESCRIPTION
**Pull request by jpf91**
```
libphobos/ChangeLog:

2019-03-02  Johannes Pfau  <johannespfau@gmail.com>

	* configure.ac: Update comment for autotool versions. 

```

### CODE REVIEW

**Comment by jpf91** [comment]
Ping @ibuclaw this should be trivial I guess?

**Review by belka-ew — APPROVED** [review]

**Comment by belka-ew** [comment]
It seems I don't have write access to the new repositories anymore. And I kind of overlooked the latest PRs since I wasn't watching that repositories, mea culpa.

**Comment by jpf91** [comment]
@ibuclaw  BTW, what is our review policy? If something (gdc/libphobos only of course) is approved here on Github, can I push this directly to GCC+svn and then only send a PATCH, committed message to the ML?

**Comment by jpf91** [comment]
@belka-ew sorry, the repo is still new, I'll have a look why you don't have write access :-) However, we only use this for the CI and review, we never merge pull requests here. Instead we submit reviewed changes to GCC svn and a cron job then updates the`trunk` branch in this repo once a day to match GCC SVN.

**Comment by ibuclaw** [comment]
> BTW, what is our review policy? If something (gdc/libphobos only of course) is approved here on Github, can I push this directly to GCC+svn and then only send a PATCH, committed message to the ML?

As you formally have write-after-approval, patch would still need to be sent to gcc-patches and myself or some other maintainer replying with OK.  Adding me to the Cc is a sure way that I'll pick it up quickly.

If a change is obvious, then you can just skip approval and just commit and post to gcc-patches.

Whether or not a change is obvious I'll leave to your discretion, however by rule of thumb if you think no one will object, just go for it.

This PR is an obvious change.

**Comment by jpf91** [comment]
OK, committed as obvious and sent patch to gcc-patches.

**Pull request closed without merging**
